### ISSUE TITLE
Add a user type field

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/dashboard#15]
We already have the system that assigns users GP credits for sponsoring, but we also need an attribute on the user like `isActiveSponsor: boolean` that can be used for UI customizations and enabling some extra non-GP features. For one-time sponsors, this should probably say `false` all the time.

**Comment by alexey-yarmosh** [comment]
We have a `sponsors` collection which is in sync with github and have only actual recurring sponsors.

**Comment by jimaek** [comment]
To clarify the dashboard needs:
- one time donation = Member, same as free users
- recurring sponsor = Sponsor
- special account = Custom limits and UI tag

**Comment by MartinKolarik** [comment]
Ok, so let's change this to an enum actually to support multiple values, starting with `member`, `sponsor, and `special` ? Member is the default, sponsor gets automatically set/unset, and special can be set manually by us.

@jimaek what's the priority special > sponsor or the opposite? For cases when a special starts sponsoring.

**Comment by jimaek** [comment]
Special is highest
