### ISSUE TITLE
Staging server

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/dashboard#24]
Before we make the dashboard public, we should set up a separate staging environment. I'm thinking a separate render.com service, and the DB server can stay the same, just use a separate database.

**Comment by MartinKolarik** [comment]
@jimaek please create a new `dashboard-staging` DB and its own user and send me the credentials.

**Comment by jimaek** [comment]
DOne

**Comment by MartinKolarik** [comment]
Available at https://dashboard-staging-jsdelivr-com.onrender.com, I copied data from prod, so we all have accounts, and registration is disabled. Deploys by triggering a build [here](https://github.com/jsdelivr/dashboard/actions/workflows/docker-staging.yml) and then manually in Render.
