### ISSUE TITLE
Probe adoption issue

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/dashboard#26]
I've run several times into a situation where the API took more than 5 seconds to respond, so we run into a timeout [here](https://github.com/jsdelivr/dashboard/blob/84a1e161961f6978221cf4397c5b39d76039b46d/src/extensions/endpoints/adoption-code/src/index.ts#L80) and didn't store the code as valid. However, the probe actually did get the code a second later, and it was confusing the code didn't work then.

Partly, this is a problem of not showing the timeout error in the current UI, but I think we could also store the code regardless of the API response. If the user happens to get it, they can use it without issues, even if the request "timed out". If the user doesn't get it, they'll request a new one that overrides the old one, so no harm is done.

**Comment by jimaek** [comment]
Why does the API take 5seconds anyway? Can we speed it up as well?

**Comment by alexey-yarmosh** [comment]
For that operation API uses `fetchSockets`, which has perf issues. So fixing underlying issue is related to https://github.com/jsdelivr/globalping/issues/307 and https://github.com/jsdelivr/globalping/issues/419
