### ISSUE TITLE
Deleting accounts

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/dashboard#31]
Users must be able to delete their accounts. This means:
 - adopted probes are deleted,
 - existing credits and their history are deleted (though if they keep sponsoring, new additions will appear over time),
 - tokens are deleted,
 - sponsor records are kept as before.

**Comment by jimaek** [comment]
>existing credits and their history - not sure, @jimaek ?

As long as we clearly warn the user he will lose them, we should delete credits/history too.
