### ISSUE TITLE
Geodata of an IP range

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/dashboard#39]
Need to implement a way for an admin to modify the geodata of an IP range using dashboard. 

Users should be able to overwrite the admin on adopted probes.

**Comment by jimaek** [comment]
Cidr is fine. So it should support:
- 1.1.1.1/8
- and single IPs 2.2.2.2/32

**Comment by alexey-yarmosh** [comment]
Rebuilding of probes list happens every 2 seconds, during it every probe is validated through the list of CIDRs. That gives N*M complexity, which should be ok for a few admin overrides, but for large lists a CIDR trie should be used for lookups (e.g. https://cidr-trie.readthedocs.io/en/latest/). I didn't found a similar lib for js, but it can be written ourselves.

**Comment by MartinKolarik** [comment]
We could also compare the timestamp of last admin change vs the applied one and only modify existing probes when it differs + always do it on probe connection. Most of the time that would mean no-op during sync.

**Comment by alexey-yarmosh** [comment]
True. It may look like a cache of search results, which is only purged when the timestamps of admin change differs.
